{
  config,
  root,
  lib,
  ...
}: let
  cfg = config.modules.hyprland;
  mkInline = lib.generators.mkLuaInline;
in {
  config = lib.mkIf cfg.enable {
    home.file = {
      # Hand-edited Lua fragments. ~/.config/hypr/hyprland.lua itself is
      # generated by Home Manager (configType = "lua" below); we only
      # symlink the parts/ subdirectory and dofile it from extraConfig.
      ".config/hypr/parts" = {
        source =
          config.lib.file.mkOutOfStoreSymlink
          (builtins.toPath "${root}/static/hypr/parts");
      };
    };

    # Previously set via Hyprland's `env = [...]` directive. The Lua API
    # for env vars isn't documented; we set them at the shell level instead.
    home.sessionVariables = {
      XCURSOR_THEME = "Catppuccin Mocha Dark";
      XCURSOR_SIZE = "24";
      HYPRCURSOR_SIZE = "24";
      AQ_NO_MODIFIERS = "1";
    };

    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      # systemd.enable auto-emits hl.exec_cmd("dbus-update-activation-environment ...")
      # inside hl.on("hyprland.start", ...) — and sets up hyprland-session.target.
      systemd.enable = true;
      # Generate hyprland.lua (the modern format) instead of hyprland.conf.
      # Requires home-manager with the `configType` option (>= 2026-XX).
      configType = "lua";

      settings = {
        # Single monitor catch-all. Multiple monitors → list of attrs.
        monitor = {
          output = "";
          mode = "preferred";
          position = "auto";
          scale = 1;
        };

        config = {
          general = {
            gaps_in = 3;
            gaps_out = 6;
            border_size = 0;
          };
          input = {
            kb_layout = "us";
            kb_variant = "";
            kb_model = "";
            kb_rules = "";
            kb_options = "";
            follow_mouse = 1;
            sensitivity = 0;
            touchpad = {
              natural_scroll = true;
              clickfinger_behavior = false;
              disable_while_typing = false;
              tap_and_drag = false;
            };
          };
          cursor = {
            inactive_timeout = 3;
            no_hardware_cursors = 1;
          };
          decoration = {
            rounding = 8;
            active_opacity = 1;
            inactive_opacity = 1;
            dim_inactive = true;
            dim_strength = 0.1;
            blur = {
              enabled = true;
              size = 6;
              passes = 2;
              new_optimizations = true;
              ignore_opacity = true;
            };
            shadow = {
              enabled = true;
              range = 5;
              render_power = 3;
              offset = [0 0];
              color = "rgba(17,17,27,1.0)";
              color_inactive = "rgba(17,17,27,0.0)";
            };
          };
          group = {
            groupbar = {
              font_family = "SFMono";
              font_size = 14;
              gradients = true;
            };
          };
          binds = {
            movefocus_cycles_fullscreen = false;
            workspace_center_on = 1;
            focus_preferred_method = 0;
          };
          animations.enabled = true;
          dwindle = {
            pseudotile = true;
            preserve_split = true;
            force_split = 2;
            default_split_ratio = 1;
          };
          master.new_status = "slave";
          misc = {
            disable_hyprland_logo = true;
            mouse_move_enables_dpms = true;
            key_press_enables_dpms = true;
            force_default_wallpaper = -1;
          };
          gestures = {
            workspace_swipe_invert = true;
            workspace_swipe_distance = 700;
          };
        };

        # hl.curve(name, { type = ..., points = ... }) — multi-arg.
        curve = [
          {
            _args = [
              "slow"
              {
                type = "bezier";
                points = [[0 0.85] [0.3 1]];
              }
            ];
          }
          {
            _args = [
              "overshot"
              {
                type = "bezier";
                points = [[0.7 0.6] [0.1 1.1]];
              }
            ];
          }
          {
            _args = [
              "bounce"
              {
                type = "bezier";
                points = [[1 1.6] [0.1 0.85]];
              }
            ];
          }
          {
            _args = [
              "slingshot"
              {
                type = "bezier";
                points = [[1 (-1)] [0.15 1.25]];
              }
            ];
          }
          {
            _args = [
              "myBezier"
              {
                type = "bezier";
                points = [[0.05 0.9] [0.1 1.05]];
              }
            ];
          }
        ];

        # speed is in ds (1ds = 100ms)
        animation = [
          {
            leaf = "windows";
            enabled = true;
            speed = 7;
            bezier = "myBezier";
          }
          {
            leaf = "windowsOut";
            enabled = true;
            speed = 7;
            curve = "default";
            style = "popin 80%";
          }
          {
            leaf = "border";
            enabled = true;
            speed = 10;
            curve = "default";
          }
          {
            leaf = "fade";
            enabled = true;
            speed = 7;
            curve = "default";
          }
          {
            leaf = "workspaces";
            enabled = true;
            speed = 6;
            curve = "default";
          }
        ];

        gesture = {
          fingers = 3;
          direction = "horizontal";
          action = "workspace";
        };

        window_rule = [
          {
            match.class = ".*";
            suppress_event = "maximize";
          }

          {
            match.class = "^(firefox)$";
            opacity = "1.0 1.0";
          }
          {
            match.class = "^([Ss]team)$";
            opacity = "0.70 0.70";
          }
          {
            match.class = "^(steamwebhelper)$";
            opacity = "0.70 0.70";
          }
          {
            match.class = "^([Ss]potify)$";
            opacity = "0.70 0.70";
          }
          {
            match.initial_title = "^(Spotify Free)$";
            opacity = "0.70 0.70";
          }
          {
            match.initial_title = "^(Spotify Premium)$";
            opacity = "0.70 0.70";
          }

          {
            match.class = "^(discord)$";
            opacity = "0.80 0.80";
          }
          {
            match.class = "^(WebCord)$";
            opacity = "0.80 0.80";
          }
          {
            match.class = "^(ArmCord)$";
            opacity = "0.80 0.80";
          }

          {
            match = {
              class = "^(org.kde.dolphin)$";
              title = "^(Progress Dialog — Dolphin)$";
            };
            float = true;
          }
          {
            match = {
              class = "^(org.kde.dolphin)$";
              title = "^(Copying — Dolphin)$";
            };
            float = true;
          }
          {
            match.title = "^(About Mozilla Firefox)$";
            float = true;
          }
          {
            match = {
              class = "^(firefox)$";
              title = "^(Picture-in-Picture)$";
            };
            float = true;
          }
          {
            match = {
              class = "^(firefox)$";
              title = "^(Library)$";
            };
            float = true;
          }
          {
            match = {
              class = "^(kitty)$";
              title = "^(top)$";
            };
            float = true;
          }
          {
            match = {
              class = "^(kitty)$";
              title = "^(btop)$";
            };
            float = true;
          }
          {
            match = {
              class = "^(kitty)$";
              title = "^(htop)$";
            };
            float = true;
          }
          {
            match.class = "^(vlc)$";
            float = true;
          }
          {
            match.class = "^(kvantummanager)$";
            float = true;
          }
          {
            match.class = "^(qt5ct)$";
            float = true;
          }
          {
            match.class = "^(qt6ct)$";
            float = true;
          }
          {
            match.class = "^(nwg-look)$";
            float = true;
          }
          {
            match.class = "^(org.kde.ark)$";
            float = true;
          }
          {
            match.class = "^(org.pulseaudio.pavucontrol)$";
            float = true;
          }
          {
            match.class = "^(blueman-manager)$";
            float = true;
          }
          {
            match.class = "^(nm-applet)$";
            float = true;
          }
          {
            match.class = "^(nm-connection-editor)$";
            float = true;
          }
          {
            match.class = "^(org.kde.polkit-kde-authentication-agent-1)$";
            float = true;
          }

          {
            match.class = "^(Signal)$";
            float = true;
          }
          {
            match.class = "^(com.github.rafostar.Clapper)$";
            float = true;
          }
          {
            match.class = "^(app.drey.Warp)$";
            float = true;
          }
          {
            match.class = "^(net.davidotek.pupgui2)$";
            float = true;
          }
          {
            match.class = "^(yad)$";
            float = true;
          }
          {
            match.class = "^(eog)$";
            float = true;
          }
          {
            match.class = "^(io.github.alainm23.planify)$";
            float = true;
          }
          {
            match.class = "^(io.gitlab.theevilskeleton.Upscaler)$";
            float = true;
          }
          {
            match.class = "^(com.github.unrud.VideoDownloader)$";
            float = true;
          }
          {
            match.class = "^(io.gitlab.adhami3310.Impression)$";
            float = true;
          }
          {
            match.class = "^(io.missioncenter.MissionCenter)$";
            float = true;
          }

          {
            match.title = "^(Open)$";
            float = true;
          }
          {
            match.title = "^(Choose Files)$";
            float = true;
          }
          {
            match.title = "^(Save As)$";
            float = true;
          }
          {
            match.title = "^(Confirm to replace files)$";
            float = true;
          }
          {
            match.title = "^(File Operation Progress)$";
            float = true;
          }
          {
            match.class = "^(xdg-desktop-portal-gtk)$";
            float = true;
          }

          {
            match.title = "^(pop-up)$";
            float = true;
            pin = true;
            size = [800 600];
          }
        ];

        layer_rule = [
          {
            match.namespace = "waybar";
            blur = true;
          }
          {
            match.namespace = "tofi";
            blur = true;
          }
          {
            match.namespace = "swaync";
            blur = true;
          }
        ];
      };

      # Bridge into hand-edited Lua: define globals here so they're a single
      # source of truth in Nix, then load parts/keybinds.lua which uses them.
      extraConfig = ''
        -- Globals (injected from Nix; usable inside dofile'd parts/)
        mainMod = "SUPER"
        terminal = "ghostty"
        webBrowser = "firefox"
        menu = "vicinae toggle"
        -- fileManager = "nautilus"
        -- notes = "obsidian"

        -- Live-edited fragments (symlinked from static/hypr/parts/)
        dofile(os.getenv("HOME") .. "/.config/hypr/parts/keybinds.lua")
      '';
    };
  };
}
