{
  config,
  root,
  lib,
  pkgs,
  ...
}: let
  cfg = config.modules.hyprland;
in {
  config = lib.mkIf cfg.enable {
    # nixpkgs' own catppuccin-cursors (pre-built, cached on cache.nixos.org)
    # rather than catppuccin/nix's own from-source cursor build. Sets
    # XCURSOR_THEME/XCURSOR_SIZE itself (via mkDefault) — nothing else here
    # should override those.
    home.pointerCursor = {
      package = pkgs.catppuccin-cursors.mochaDark;
      name = "catppuccin-mocha-dark-cursors";
      size = 24;
    };

    home.file = {
      # Hand-edited Lua. ~/.config/hypr/hyprland.lua itself is generated by
      # Home Manager (configType = "lua" below); the generated file require's
      # everything in parts/ via extraConfig.
      ".config/hypr/parts" = {
        source =
          config.lib.file.mkOutOfStoreSymlink
          (builtins.toPath "${root}/static/hypr/parts");
      };
    };

    # Previously set via Hyprland's `env = [...]` directive. The Lua API
    # for env vars isn't documented; we set them at the shell level instead.
    # XCURSOR_THEME/XCURSOR_SIZE come from home.pointerCursor above.
    home.sessionVariables = {
      HYPRCURSOR_SIZE = "24";
      AQ_NO_MODIFIERS = "1";
    };

    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      # Auto-emits hl.exec_cmd("dbus-update-activation-environment ...")
      # inside hl.on("hyprland.start", ...) — and sets up hyprland-session.target.
      systemd.enable = true;
      # Generate hyprland.lua (the modern format) instead of hyprland.conf.
      # Requires home-manager with the `configType` option.
      configType = "lua";

      # All real config lives in static/hypr/parts/*.lua, symlinked into
      # ~/.config/hypr/parts above and require'd below.
      extraConfig = ''
        require("parts")
      '';
    };
  };
}
